version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.141.59-20201119
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub


  hub:
    image: selenium/hub:3.141.59-20201119
    ports:
      - "4444:4444"